services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
      - "5400:5400"
    env_file:
      - ./.env.production
    depends_on:
      postgres:
          condition: service_healthy
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_data: