import type { Metadata } from 'next'
import { Baloo_2 } from 'next/font/google'

import { AppChildren } from '~/types'

import { AuthGuard } from '~/components/auth-guard'
import { AppLayout } from '~/components/layout-root'
import { Providers } from '~/components/providers'

import { cn } from '~/lib/utils'

import '~/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const baloo = Baloo_2({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800']
})

const RootLayout = ({ children }: Readonly<AppChildren>) => (
  <html lang="pt">
    <body className={cn(baloo.className, 'dark')}>
      <Providers>
        <AuthGuard>
          <AppLayout>{children}</AppLayout>
        </AuthGuard>
      </Providers>
    </body>
  </html>
)

export default RootLayout
